module top (
    input         CLK100MHZ,    // system clock for display scanning
    input  [8:0]  SW,           // SW[3:0]=addr, SW[7:4]=write data, SW[8]=mem select
    input         BTNC,         // clock for memories (manual button press)
    input         BTNU,         // write enable
    output [6:0]  SEG,          // 7-segment cathodes (active-low)
    output [7:0]  AN            // 7-segment anodes (active-low)
);

  // --- Address and data from switches ---
  wire [3:0] addr  = SW[3:0];
  wire [7:0] wdata = {4'b0000, SW[7:4]};  // only write lower 4 bits
  wire       sel   = SW[8];                // 0=regfile, 1=RAM

  // --- Write enable routing ---
  wire reg_we = BTNU & ~sel;   // write to regfile when sel=0
  wire ram_we = BTNU &  sel;   // write to RAM when sel=1

  // ======================================================
  // Register File (async read, sync write on BTNC posedge)
  // ======================================================
  wire [7:0] reg_rdata;
  regfile16x8 u_regfile (
      .clk   (BTNC),
      .we    (reg_we),
      .addr  (addr),
      .wdata (wdata),
      .rdata (reg_rdata)
  );

  // ======================================================
  // Block RAM IP (single-port, sync read/write on BTNC posedge)
  // Generated by Tcl script as blk_mem_gen_0
  // Port A: 16-deep x 8-bit, .coe initialized
  // ======================================================
  wire [7:0] ram_rdata;
  blk_mem_gen_0 u_ram (
      .clka  (BTNC),
      .wea   (ram_we),
      .addra (addr),
      .dina  (wdata),
      .douta (ram_rdata)
  );

  // ======================================================
  // Display: 8-digit multiplexed 7-segment
  // AN[7:4] (left) = RAM output,  AN[3:0] (right) = regfile output
  // Each value is 8-bit, displayed as 2 hex digits
  // Unused digits show 'F' pattern (all segments off via hex7seg default)
  // ======================================================
  // Layout: [AN7 AN6 AN5 AN4 | AN3 AN2 AN1 AN0]
  //         [  --  -- ram_hi ram_lo |  --  -- reg_hi reg_lo]
  // Use 0xF for blank digits (hex7seg outputs all-off for 0xF)
  // Actually 0xF will show "F" letter. Let's just put the data there.
  // For clean display, we put data in the lowest 2 digits of each half.
  wire [31:0] display_data = {
      4'h0, 4'h0, ram_rdata[7:4], ram_rdata[3:0],    // AN[7:4]: RAM
      4'h0, 4'h0, reg_rdata[7:4], reg_rdata[3:0]     // AN[3:0]: regfile
  };

  display8 u_display (
      .clk  (CLK100MHZ),
      .data (display_data),
      .an   (AN),
      .seg  (SEG)
  );

endmodule
